### ISSUE TITLE
unify scripts

### ISSUE THREAD

**Issue by casperdcl** [SyneRBI/SIRF-SuperBuild#91]
Build scripts are currently littered everywhere, meaning redundancy and possible inconsistency:

- `SuperBuild/`
    + `.travis.yml`
    + `docker/`
- `VM`
- `SIRF/`
    + `.travis.yml`

We need a new structure:

- `SuperBuild/`
    + `.travis.yml` (refers to `scripts/travis/`)
    + ~~`scripts/`~~ just in the root
        * `common/*.sh`
        * `docker/` (refers to `common/`)
        * `vm/` (refers to `common/`)
        * `travis/` (refers to `common/`)
        * any mandatory `docker`/`vm` config files which require being in a parent directory of `common/`
- `SIRF`
    + `.travis.yml` (refers to `SuperBuild/`~~`scripts/`~~`travis/`)

# TODO

- [ ] extract bits of `SuperBuild/.travis.yml` -> `SuperBuild/`~~`scripts/`~~`travis|common`
    + [ ] make `SIRF/.travis.yml` use `SuperBuild/`~~`scripts/`~~`travis`
- [ ] move `SuperBuild/docker` -> `SuperBuild/`~~`scripts/`~~`docker|common|.`
- [ ] move `VM/` -> `VM/`~~`scripts/`~~`vm|common|.`
    + [ ] merge `VM` into `SuperBuild`
- [ ] 🎉

**Comment by paskino** [comment]
@casperdcl I don't understand correctly. 
Where I to add the VM scripts where should they go?
Additionally, if I understand correctly you plan to move the current SuperBuild files under a `SuperBuild` directory.

**Comment by KrisThielemans** [comment]
I suggest we discuss this in the tcon on Friday. let's not make any changes until after 1.0.0 of course

**Comment by casperdcl** [comment]
@paskino I'd intended for you to create a "scripts" directory in the root of VM repo. Nothing else should be in the root. "scripts" will contain 2 subfolders: "vm", and "common", which will contain scripts that are vm-specific and generic, respectively. This would make it easy to merge the VM repo with the SuperBuild repo.

**Comment by KrisThielemans** [comment]
proposed structure

- root dir
   - any mandatory docker/vm config files 
    - README
    - CHANGES etc
    -  .travis.yml (refers to scripts/travis/)
    - .appveyor.yml
-  common_scripts/*.sh
-  docker/ (refers to common/)
-    vm/ (refers to common/)
     -   scripts
      -  vagrant
 - travis/ (refers to common/)
-  CMake
    -  CMakeModules
     - SuperBuild

**Comment by KrisThielemans** [comment]
steps.
1. create new branch on VM
2. move files according to correct dir structure
3. create branch in this repo
4. merge VM branch into that branch this repo
5. move other files in this repo to correct place
5. start to move things to `common_scripts`

**Comment by KrisThielemans** [comment]
This is too ambitious for v2.0 I believe. I suggest to postpone

**Comment by bathomas** [comment]
> This is too ambitious for v2.0 I believe. I suggest to postpone

Agree. Should also consider cloud(s) inclusion/exclusion in this.

**Comment by KrisThielemans** [comment]
would have to be done such that top-level dir contains `CMakeLists.txt` for backwards compatibility.

When moving things, would it be better to merge PRs first?

**Comment by casperdcl** [comment]
merge PRs in the VM repo (https://github.com/CCPPETMR/CCPPETMR_VM/pulls), sure

**Comment by KrisThielemans** [comment]
This is as good as completed now. Probably some scope for cleaning later.
